### ISSUE TITLE
CORS ISSUE

### ISSUE THREAD

**Issue by adnanzzz11** [akshayanandraut/api-utc#1]
Hey, when i do a get i get the following error:
XMLHttpRequest cannot load https://akshayanand.herokuapp.com/api/utc/?location=IN&format=JSON. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3000' is therefore not allowed access.

I think you need to add the CORS headers or so in your API, correct me if i'm wrong

**Comment by akshayanandraut** [comment]
Okay. Thank you for reporting this.
The issue is solved now.

**Comment by adnanzzz11** [comment]
Yeah it works now! 

Thank you!
